# -*- coding: utf-8 -*-
"""aula 10 curso em video 16/02/2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gU1pOrwA9EqKzY2_2tbnN_O5Us6rO80U
"""

real = float(input('Quanto dinheiro você tem na carteira?'))
 dólar = real / 3.27
 print('com R${} você pode compar U$${}'.format(real, dólar))