# -*- coding: utf-8 -*-
"""aula curso em video1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CuLjgigg74IG-_ygP8Wzr8YTnIqu5TQ7
"""

n1 = int(input('digite um valor:'))
n2 = int(input('Digite outro:'))
s = n1 + n2
print('------A soma vale-----', s )
print('a soma entre {} e {} vale {}' .format(n1, n2 ,s))

