# -*- coding: utf-8 -*-
"""aula 01/02/2022 - conversor de medidas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19aF3Wb8mcJ7O1qfuHLbz9guqpHzesR3Y
"""

medida = float(input('uma distância em metros:'))
cm = medida * 100
mm = medida *1000
print('A media de {}m corresponde a {} e {}mm'.format(medida, cm ,mm))