# -*- coding: utf-8 -*-
"""aula 14 curso em video 17/02/2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CPy1DyA2zrMYbAOocdindydP_8SN8DbT
"""

c = float(input('Informe a temperatura em °c:'))
f = ((9 * c) / 5) + 32
print('A temperatura de {} °c corresponde a {}°F!'.format(c, f ))