# -*- coding: utf-8 -*-
"""aula 11 curso em video 16/02/2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XPoAyGqqkbNbYyOTlfhWsdtNk8Af3aqw
"""

larg = float(input('largura da parede:'))
alt = float(input('Altura da parede:'))
área = larg = alt
print('sua parede tem a dimensão de {} x {} e sua área é de {}m²'.format(larg, alt, área))