# -*- coding: utf-8 -*-
"""aula curso em video3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MsHnTeIzwPO81W-Lba1-SLU6ckIAPds8
"""

from math import sqrt, floor
num = int(input('digite um numero:'))
raiz = math.sqrt(num)
print('A raiz de {} é igual a {}' .format(num, floor(raiz)))

import random
num = random.randint(1 ,10)
print(num)

