# -*- coding: utf-8 -*-
"""aula 13 curso em video 16/02/2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G7KCMBvXcI40n4bN5hVeOKRNlo8LvnRi
"""

salário = float(input('digite o salário do funcionário: R$'))
novo = salário + (salário * 15 / 100)
print(' o salário do funcionário que era de R${} com 15% de aumento,passa a receber {}'.format(salário , novo))

