# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QWW7RHFXLQMhFuOmUR37qWuPtSR8PgLh
"""



nome_do_usuario = input("Escreva Nome do Usuário:")
print("Seja Bem vindo!" , nome_do_usuario)
ano_atual = int(input("Escreva Ano Atual:"))
ano_de_nascimento = int(input("Ano de Nascimento :"))
print("Sua Idade é:" , (ano_atual - ano_de_nascimento) )