# -*- coding: utf-8 -*-
"""conversor de grau celsius.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MQGFx8EqZ8PZAbIXgbfFaZo-5fHefIn1
"""

c = float(input('informe a temperatura em °c:'))
 f = ((9*c)/5)+32
print('a temperatura de {} °c corresponde a {} °f'.format(c, f))