# -*- coding: utf-8 -*-
"""Curso em video aula2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nlswfu4YVg9KLiQwCI0PWVue0H5APZpO
"""

n =input('digite um algo:') 
print(n.isnumeric())

numero1 =int(input('digite um  número:'))
numero2 =int(input('digite outro numero:'))
print('a soma dos números é', numero1 + numero2 )
print('----Parabéns----')