# -*- coding: utf-8 -*-
"""Curso em video aula dia 19/01/2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nlswfu4YVg9KLiQwCI0PWVue0H5APZpO
"""

n =input('digite um algo:') 
print(n.isnumeric())

numero1 =int(input('digite um  número:'))
numero2 =int(input('digite outro numero:'))
print('a soma dos números é', numero1 + numero2 )
print('----Parabéns----')

a = input('digite algo:')
print('o tipo primitivo desse valor é:' , type(a))

5 + 3 * 2
5**2
19//2
19/2
356**522
18%2
122%3
pow(4,3)
81**(1/2)
25**(1/2)
127**(1/3)

'oi + olá'
'oi' *5
print(' =' * 20)

nome = input('Qual é seu nome:')
print('Prazer em te conhecer' .format(nome))

n1 = int(input('Um valor:'))
n2 = int(input('ouro valor:'))
s = n1 + n2
m = n1 * n2
d = n1 / n2
di = n1 // n2
e = n1 ** n2
print(' a soma {}, o produto é {} e a divisão é {}'.format(s,m,d))
print(' divisão interia {} e potencia  {} '.format(di, e))