# -*- coding: utf-8 -*-
"""curso em video aula dia 20/01/2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ET9cHAJRznvCtO6qcj0na2CC_RsnJJBU
"""

#análise
frase ='ola mundo'
frase.count('a') #encontrar letras
frase.find('mun')
frase.find('android')
frase.replace('mundo','python') #mudar nome
frase.upper()
frase.lower()
frase.capitalize()
frase.title()
frase.strip()
frase.rstrip()
frase.lstrip()

#divisão
frase.split()

#junção
'-'.join(frase)

frase = 'curso em video python'
print(frase[3::2])
print('oi')

print(frase.upper().count('o'))
print(len(frase.strip()))
print(frase.replace('python','android'))
print(frase.lower().find('video'))
dividido = (frase.split()