# -*- coding: utf-8 -*-
"""curso em video aula 007/ 01/02/2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wua0fXNfthU34wRxNHC7O_TGQOltsVcF
"""

n1 = float(input('Primeira nota do aluno:'))
n2 = float(input('Segunda nota do aluno:'))
média = (n1 + n2) / 2
print('A média entre {} e {} é igual a {}'.format(n1, n2, média))