# -*- coding: utf-8 -*-
"""curso em video 01/02/2022 - exercico  tabuada 009.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DxiVzAr-plLs-9RucYELcSa45e5npczY
"""

num = int(input('Digite um número para ver sua tabuada:'))
print('-' * 12)
print('{} x {:2} = {}'.format(num, 1,num*1))
print('{} x {:2} = {}'.format(num, 2,num*2))
print('{} x {:2} = {}'.format(num, 3,num*3))
print('{} x {:2} = {}'.format(num, 4,num*4))
print('{} x {:2} = {}'.format(num, 5,num*5))
print('{} x {:2} = {}'.format(num, 6,num*6))
print('{} x {:2} = {}'.format(num, 7,num*7))
print('{} x {:2} = {}'.format(num, 8,num*8))
print('{} x {:2} = {}'.format(num, 9,num*9))
print('{} x {:2} = {}'.format(num, 10,num*10))
print('-' * 12)