# -*- coding: utf-8 -*-
"""curso em video desafio 22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C0pDdVVx5b8xkK6aATabU6qWxNYhDov_
"""

#desafio 22 
nome = input('Digite Seu Nome:')
print('olá',nome)
print(nome.upper())
print(nome.lower())
print(nome.count(nome))

