# -*- coding: utf-8 -*-
"""estudo de python9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E9HwGJj-8j7bhWIEUpz7OLf99ZEU-L1U
"""

print('olá,mundo!')



print('oi')

print('oi')
print('tudo bem')

#isso é um cometário
print('oi')

(5+6)

