# -*- coding: utf-8 -*-
"""estudo python aula 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nal8GFSWHyfIgyXkpw6Njv2dRxXM9QFX
"""

var = 4
var2 = 3.5
type(var2)
palavra = 'frase 1'
type(palavra)

print(var + var2)

print(var + palavra)