# -*- coding: utf-8 -*-
"""estudo de pyhton aula 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NoHySeQmt2G8fxJcWin4G5adUCZcFDmD
"""

print(10+5)
print(5*5)
print(17/3)
print(2**3)

print(5//2)

print(5%2)