# -*- coding: utf-8 -*-
"""estudo de python aula3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VT4KJcHtlxmYJiQ1sMnnFcAHt08bEGp2
"""

a = 5 
a == 3

b = 7
c =  a + b
print(b)

variavel1 = 3 
variavel2 = 4
variavel1 = 9
print(variavel1)

b = 11