# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i3M9NUuxjfUadmrOBIu2aaZWNZV7snk3
"""

salario_mensal = input
salario_mensal = float(input("escreva o valor do salário:"))
horas_trabalhadas_por_mes = input
horas_trabalhadas_por_mes = float(input("escreva horas trabalhadas:"))
valor_hora = salario_mensal/ horas_trabalhadas_por_mes
print (valor_hora)