# -*- coding: utf-8 -*-
"""primeiro código sozinha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_45snRTOPh0XOdXd-R5DNzyvnf_D0x2J
"""

senha1 = int(input('Digite a primeira senha:'))
senha2 = int(input('Digite a segunda senha:')) 
if senha1 > senha2 :
  print('Pode passar!')
  print('------Parabéns------')

else :
 print('Não pode passar')
 print('------Tente mais tarde------')