# -*- coding: utf-8 -*-
"""python aula10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ac_4IJOioMcZuF2gJtmvRIsqQ5OsLeh4
"""

import time
contador = 0
while contador < 10:
  print('ainda não deu')
  contador = contador + 1
  if contador == 6:
      break
  time.sleep(1)
print('agora deu')