# -*- coding: utf-8 -*-
"""python aula 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TeeUnlOcn4jcQJP1rpwpDB9phbZr1BHX
"""

fruta = 'limão'

print('suco de %s é o meu favorito' %fruta)

print('suco de {} é o meu favorito' .format(fruta))

cor1 = 'azul'
cor2 = 'rosa'
print('o céu é {0}, a flor é {1} e meu carro é {0}'.format(cor1,cor2))

conta = 17/3
print(conta)

print('o resultado da conta é: {:.2f}'.format(conta))