# -*- coding: utf-8 -*-
"""python aula 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l_G1rVfV5iAHcgO8p-l0qnwyb-zl7cfL
"""

nome = input('qual o seu nome?:')



print(nome)

idade = input('qual a sua idade?:')

print(idade)

print(idade*2)

type(idade)

idade = int(input('qual a sua idade?:'))

type(idade)

print(idade*2)