# -*- coding: utf-8 -*-
"""python aula12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JerifBnMVSmS86LS5qgpm8TWMOu_FLtG
"""

def parabens():
   print('parabéns para você\n nessa data querida\n muitas felicidades\n muitos anos de vida!')
parabens()

def temletrau():
  frase = input('digite uma frase:')
  if'u'  in frase:
    print('você utilizou a letra U')
  else:
      print('você não utilizou a letra U')

temletrau()

def somaquadrados(a,b):
  somaQ = a**2 + b**2
  return somaQ

somaquadrados(2,3)