# -*- coding: utf-8 -*-
"""python aula11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PiVchNMX2X-joaMdBpq9zeJN-Mg6ZV2W
"""

import math
math.factorial(5)

import datetime
datetime.date.today()

import datetime
datetime.date.isoformat(datetime.date.today())

from datetime import date
date.isoformat(date.today())