# -*- coding: utf-8 -*-
"""retornar valor escolhido atualização.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BdFfJdOVlqX_ywzW0BW-A2Lf54BSX6u2
"""

numero_secreto = 42
chute_str = input('Digite o seu numero:')
acertou = numero_secreto == chute
maior = chute > numero_secreto
menor = chute < numero_secreto
print('Você digitou', chute_str)
chute= int(chute_str)
if(numero_secreto == chute):
  print('você acertou!')
else :
  if(maior):
    print('Você errou!, O seu numero foi maior do que o numero secreto')
  elif(menor):
      print('Você errou! O seu chute foi maior do que o numero secreto')

print('-----Fim do jogo-----')