# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hXzxOzWdbmrxMA0-b7kK4GkJilqsSsF5
"""



preco_produto = float(input("escreva o preço do produto:"))
valor_dinheiro =float(input("escreva valor do dinheiro:"))

if preco_produto > valor_dinheiro:
  print("você não tem o valor suficiente!")
else:
  print("o troco a ser dado é:", valor_dinheiro - preco_produto)